export const SET_SELECTED_COUNTRY = 'SET_SELECTED_COUNTRY';
export const SET_SELECTED_PORT = 'SET_SELECTED_PORT';
export const SET_PORTS = 'SET_PORTS';
export const SET_BARANG = 'SET_BARANG';
export const SET_BARANG_RESPONSE = 'SET_BARANG_RESPONSE';
export const SET_HARGA = 'SET_HARGA';
export const SET_TARIF_BEAMASUK = 'SET_TARIF_BEAMASUK';
export const SET_TOTAL = 'SET_TOTAL';
